# Generated by Django 4.0.4 on 2022-05-13 14:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('UserId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NomeCompleto', models.CharField(max_length=255)),
                ('Email', models.EmailField(error_messages={'unique': 'O email cadastrado já existe.'}, max_length=254, unique=True)),
                ('Senha', models.CharField(max_length=30)),
                ('CPF', models.CharField(max_length=11, unique=True)),
            ],
        ),
    ]
