# Generated by Django 4.0.4 on 2022-05-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITRApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='DataNasc',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='NomeFoto',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
