# Generated by Django 4.0.4 on 2022-05-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITRApp', '0003_remove_usuario_nomefoto_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Curriculo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
