# Generated by Django 4.0.4 on 2022-05-13 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CITRApp', '0005_usuario_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Telefone',
            new_name='Celular',
        ),
    ]
