# Generated by Django 4.0.4 on 2022-05-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITRApp', '0006_rename_telefone_usuario_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Celular',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
