# Generated by Django 4.0.4 on 2022-05-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITRApp', '0007_alter_usuario_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='CEP',
            field=models.CharField(default=0, max_length=9),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Descricao',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Celular',
            field=models.CharField(default=0, max_length=13),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='DataNasc',
            field=models.DateField(),
        ),
    ]
