# Generated by Django 4.0.4 on 2022-05-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITRApp', '0008_usuario_cep_usuario_descricao_alter_usuario_celular_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='DataNasc',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='CEP',
            new_name='cep',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='CPF',
            new_name='cpf',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Curriculo',
            new_name='cv',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Celular',
            new_name='fone',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='NomeCompleto',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Senha',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Foto',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='UserId',
            new_name='userId',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
