# Generated by Django 4.0.4 on 2022-05-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITRApp', '0009_rename_datanasc_usuario_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cv',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
