# Generated by Django 4.0.4 on 2022-05-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITRApp', '0010_alter_usuario_cv_alter_usuario_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cv',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
