# Generated by Django 4.0.4 on 2022-05-24 00:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CITRApp', '0012_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidacies',
            fields=[
                ('candidaturaId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userID', to='CITRApp.usuario')),
                ('vacancyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancyID', to='CITRApp.vacancy')),
            ],
        ),
    ]
