# Generated by Django 4.0.4 on 2022-05-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CITRApp', '0013_candidacies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='User',
        ),
    ]
