# Generated by Django 4.0.4 on 2022-06-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITRApp', '0017_alter_vacancy_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
