# Generated by Django 4.0.4 on 2022-06-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITRApp', '0018_alter_vacancy_cep_alter_vacancy_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='typeRemuneration',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='typeHires',
            field=models.CharField(blank=True, choices=[('CTD', 'Contrato de Tempo Determinado'), ('CTI', 'Contrato de Tempo Indeterminado'), ('CTE', 'Contrato de Trabalho Eventual'), ('CE', 'Contrato de Estágio'), ('CExp', 'Contrato de Experiência'), ('CT', 'Contrato de Teletrabalho'), ('CI', 'Contrato Intermitente'), ('CTA', 'Contrato de Trabalho Autonômo')], max_length=10),
        ),
    ]
